CREATE TABLE `cliente` (
	`ID_CLIENTE` INT(10) NOT NULL AUTO_INCREMENT,
	`NOME` VARCHAR(80) NOT NULL,
	`DATA_NASCIMENTO` VARCHAR(10) NOT NULL,
	`SEXO` VARCHAR(20) NOT NULL,
	`ESTADO_CIVIL` VARCHAR(20) NOT NULL,
	`PROFISSAO` VARCHAR(80) NOT NULL,
	`RG` VARCHAR(20) NOT NULL,
	`CPF` VARCHAR(20) NOT NULL,
	`LOGRADOURO` VARCHAR(80) NOT NULL,
	`ENDERECO` VARCHAR(80) NOT NULL,
	`NUMERO` INT(10) NOT NULL,
	`BAIRRO` VARCHAR(80) NOT NULL,
	`CEP` VARCHAR(20) NOT NULL,
	`CIDADE` VARCHAR(50) NOT NULL,
	`UF` VARCHAR(5) NOT NULL,
	`TELEFONE_RESIDENCIAL` VARCHAR(10) NOT NULL,
	`TELEFONE_COMERCIAL` VARCHAR(10) NULL DEFAULT NULL,
	`CELULAR` VARCHAR(10) NULL DEFAULT NULL,
	`EMAIL` VARCHAR(80) NULL DEFAULT NULL,
	PRIMARY KEY (`ID_CLIENTE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=5;


CREATE TABLE `animal` (
	`ID_ANIMAL` INT(10) NOT NULL AUTO_INCREMENT,
	`PROPRIETARIO` VARCHAR(80) NOT NULL,
	`NOME_COMPLETO` VARCHAR(80) NOT NULL,
	`APELIDO` VARCHAR(80) NOT NULL,
	`SEXO` VARCHAR(20) NOT NULL,
	`RGA` VARCHAR(10) NOT NULL,
	`NUM_DOC` VARCHAR(20) NOT NULL,
	`DATA_NASC` VARCHAR(10) NOT NULL,
	`ESPECIE` VARCHAR(80) NOT NULL,
	`RACA` VARCHAR(80) NOT NULL,
	`COR` VARCHAR(80) NULL DEFAULT NULL,
	`OBSERVACOES` VARCHAR(400) NULL DEFAULT NULL,
	`ID_CLIENTE` INT(10) NOT NULL,
	PRIMARY KEY (`ID_ANIMAL`),
	INDEX `ID_CLIENTE` (`ID_CLIENTE`),
	CONSTRAINT `animal_ibfk_1` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`ID_CLIENTE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2;

CREATE TABLE `produto` (
	`ID_PRODUTO` INT(10) NOT NULL AUTO_INCREMENT,
	`NOME` VARCHAR(80) NOT NULL,
	`VALOR` DOUBLE(7,2) NOT NULL,
	`DESCRICAO` VARCHAR(80) NOT NULL,
	PRIMARY KEY (`ID_PRODUTO`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=8;


CREATE TABLE `animal_especie` (
	`Id_Especie` INT(10) NOT NULL AUTO_INCREMENT,
	`Especie` VARCHAR(80) NOT NULL,
	PRIMARY KEY (`Id_Especie`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3;


CREATE TABLE `animal_raca` (
	`ID_RACA` INT(10) NOT NULL AUTO_INCREMENT,
	`RACA` VARCHAR(80) NOT NULL,
	`ID_ESPECIE` INT(10) NOT NULL,
	PRIMARY KEY (`ID_RACA`),
	INDEX `ID_ESPECIE` (`ID_ESPECIE`),
	CONSTRAINT `animal_raca_ibfk_1` FOREIGN KEY (`ID_ESPECIE`) REFERENCES `animal_especie` (`Id_Especie`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=125;

